'use client';
import {useMemo,useState} from 'react';

type Salon={id:number;name:string;area:string;rating:number;distance:string;image:string;services:string[];stylists:string[];price:number;next:string};
type Booking={id:number;salon:string;customer:string;service:string;stylist:string;slot:string;price:number;status:'Requested'|'Accepted'|'Completed'|'Cancelled';date:string};
const salons:Salon[]=[
{id:1,name:'The Groom Room',area:'Koregaon Park, Pune',rating:4.8,distance:'1.2 km',image:'💈',services:['Haircut','Beard Trim','Hair Styling'],stylists:['Aarav','Rohan'],price:299,next:'Today, 7:30 PM'},
{id:2,name:'Urban Trim Studio',area:'Viman Nagar, Pune',rating:4.7,distance:'3.4 km',image:'✂️',services:['Haircut','Beard Trim','Facial'],stylists:['Kabir','Dev'],price:349,next:'Today, 8:00 PM'},
{id:3,name:'Aarti Beauty Parlour',area:'Kalyani Nagar, Pune',rating:5.0,distance:'1.0 km',image:'🌸',services:['Haircut','Facial','Hair Styling'],stylists:['Aarti','Neha'],price:150,next:'Today, 6:30 PM'}
];
export default function Home(){
 const [selected,setSelected]=useState<Salon|null>(null); const [service,setService]=useState('Haircut'); const [stylist,setStylist]=useState(''); const [slot,setSlot]=useState(''); const [tab,setTab]=useState<'home'|'bookings'|'admin'|'owner'>('home');
 const [role,setRole]=useState(''); const [showSignup,setShowSignup]=useState(false); const [gender,setGender]=useState(''); const [query,setQuery]=useState(''); const [chatOpen,setChatOpen]=useState(false); const [chatText,setChatText]=useState(''); const [chatMessages,setChatMessages]=useState<string[]>(['Hi! I’m Shubhiii 💬 Your Trimzee helper. Need help finding a salon or booking a slot?']);
 const [ownerOnline,setOwnerOnline]=useState(true); const [salonStatus,setSalonStatus]=useState<'Available'|'Fully booked'>('Available'); const [offTime,setOffTime]=useState(''); const [bookings,setBookings]=useState<Booking[]>([]);
 const slots=useMemo(()=>['10:00 AM','11:00 AM','12:00 PM','2:00 PM','3:30 PM','5:00 PM','6:30 PM','7:30 PM','8:00 PM'],[]);
 const filtered=salons.filter(s=>(s.name+' '+s.area+' '+s.services.join(' ')).toLowerCase().includes(query.toLowerCase()));
 function confirm(){if(!selected||!stylist||!slot)return;const b:Booking={id:Date.now(),salon:selected.name,customer:'You',service,stylist,slot,price:selected.price,status:'Requested',date:new Date().toLocaleDateString()};setBookings(prev=>[b,...prev]);setSelected(null);setTab('bookings');setStylist('');setSlot('')}
 function changeBooking(id:number,status:Booking['status']){setBookings(prev=>prev.map(b=>b.id===id?{...b,status}:b))}
 function exportCSV(){const rows=[['Customer','Salon','Service','Stylist','Time','Price','Status','Date'],...bookings.map(b=>[b.customer,b.salon,b.service,b.stylist,b.slot,String(b.price),b.status,b.date])];const csv=rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='trimzee-bookings.csv';a.click();URL.revokeObjectURL(url)}
 function sendChat(){const t=chatText.trim();if(!t)return;setChatMessages(p=>[...p,'You: '+t,'Shubhiii: I can help you find a salon, choose a service, or understand a booking. For urgent booking issues, open My bookings and check the status.']);setChatText('')}
 return <main>
 <header><div className="nav"><button className="hamb" aria-label="Menu" onClick={()=>setTab(tab==='home'?'bookings':'home')}>☰</button><button className="brand" onClick={()=>setTab('home')}><span className="brandmark">T</span><span>TRIMZEE</span></button><div className="navlinks"><button onClick={()=>setTab('home')}>Discover</button><button onClick={()=>setTab('bookings')}>My bookings</button><button onClick={()=>setTab('owner')}>Salon dashboard</button><button onClick={()=>setTab('admin')}>Admin</button></div><button className="profile" onClick={()=>setShowSignup(true)} aria-label="Account">♙</button></div></header>
 {tab==='home'&&<><section className="banner container"><div className="banner-copy"><span className="eyebrow">YOUR NEXT LOOK STARTS HERE</span><h1>India’s #1 salon booking app</h1><p>Quick and free. Discover trusted salons, choose your stylist, and book your time.</p><div className="banner-actions"><button className="primary" onClick={()=>document.getElementById('salons')?.scrollIntoView({behavior:'smooth'})}>Find a salon <span>→</span></button><span className="banner-note">✦ Easy booking · No booking fee</span></div></div><div className="banner-art" aria-hidden="true"><div className="art-circle">✂</div><div className="art-tag">GOOD HAIR DAY<br/><b>starts here.</b></div><div className="art-star">✦</div></div></section>
 <section className="container search-area"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search salons or services"/><button>Search</button></div></section>
 <section className="container listing" id="salons"><div className="section-head"><div><p className="eyebrow">DISCOVER YOUR STYLE</p><h2>Nearby salons & parlours</h2><p className="muted">Choose a place and reserve a slot that works for you.</p></div><span className="result-count">{filtered.length} places</span></div><div className="grid">{filtered.map(s=><article className="salon" key={s.id}><div className={'salon-image image-'+s.id}><span className="salon-emoji">{s.image}</span><span className="open-pill">{ownerOnline&&salonStatus==='Available'?'● Available':'● Check slots'}</span></div><div className="salon-body"><div className="row"><h3>{s.name}</h3><span className="rating">★ {s.rating.toFixed(1)}</span></div><p className="area">⌖ {s.area}</p><div className="chips">{s.services.map(x=><span key={x}>{x}</span>)}</div><div className="row bottom"><div><small>STARTING FROM</small><b>₹{s.price}</b></div><button className="primary" onClick={()=>{setSelected(s);setService(s.services[0]);setStylist('');setSlot('')}}>View & book <span>→</span></button></div></div></article>)}</div>{filtered.length===0&&<div className="empty">No salons match that search. Try a service like haircut or facial.</div>}</section></>}
 {tab==='bookings'&&<section className="container page"><p className="eyebrow">YOUR APPOINTMENTS</p><h1>My bookings</h1><p className="muted">Booking details are displayed vertically for easy reading on mobile.</p>{bookings.length?bookings.map(b=><article className="booking-card vertical" key={b.id}><div className="booking-top"><span className="booking-icon">✂</span><span className={'status status-'+b.status.toLowerCase()}>{b.status}</span></div><h2>{b.salon}</h2><div className="booking-details"><p><span>Service</span><b>{b.service}</b></p><p><span>Stylist</span><b>{b.stylist}</b></p><p><span>Appointment</span><b>{b.slot}</b></p><p><span>Price</span><b>₹{b.price}</b></p></div>{b.status==='Requested'&&<button className="outline danger" onClick={()=>changeBooking(b.id,'Cancelled')}>Cancel booking</button>}</article>):<div className="empty"><div className="empty-icon">✂</div><h2>No bookings yet</h2><p>Find your favourite salon and book your first appointment.</p><button className="primary" onClick={()=>setTab('home')}>Explore salons →</button></div>}</section>}
 {tab==='owner'&&<section className="container page"><p className="eyebrow">SALON PARTNER</p><h1>Salon dashboard</h1><p className="muted">Manage availability and appointment requests.</p><div className="owner-controls"><div className="owner-switch"><div><b>Accepting bookings</b><p>{ownerOnline?'Your salon is online':'Your salon is offline'}</p></div><button className={ownerOnline?'toggle on':'toggle'} onClick={()=>setOwnerOnline(v=>!v)}>{ownerOnline?'ONLINE':'OFFLINE'}</button></div><div className="owner-switch"><div><b>Slot availability</b><p>Set fully booked when no appointments remain.</p></div><select value={salonStatus} onChange={e=>setSalonStatus(e.target.value as 'Available'|'Fully booked')}><option>Available</option><option>Fully booked</option></select></div><div className="owner-switch off-time"><div><b>Planned off time</b><p>Block a break or emergency time.</p></div><input type="time" value={offTime} onChange={e=>setOffTime(e.target.value)}/><button className="outline" onClick={()=>{if(offTime){setSalonStatus('Fully booked');alert('Off time saved for '+offTime+'. This demo marks the salon fully booked; calendar-based slot blocking needs a live database.')}}}>Save off time</button></div></div><div className="stats"><div><span>Today’s revenue</span><b>₹{bookings.filter(b=>b.status==='Completed').reduce((n,b)=>n+b.price,0)}</b></div><div><span>Monthly revenue*</span><b>₹{bookings.filter(b=>b.status==='Completed').reduce((n,b)=>n+b.price,0)}</b></div><div><span>Booking requests</span><b>{bookings.filter(b=>b.status==='Requested').length}</b></div></div><h2 className="subheading">Appointment requests</h2>{bookings.length?bookings.map(b=><article className="owner-booking" key={b.id}><div><b>{b.customer} · {b.service}</b><p>{b.slot} · {b.stylist} · ₹{b.price}</p><span className={'status status-'+b.status.toLowerCase()}>{b.status}</span></div><div className="owner-actions">{b.status==='Requested'&&<button className="primary" onClick={()=>changeBooking(b.id,'Accepted')}>Accept</button>}{b.status==='Accepted'&&<button className="primary" onClick={()=>changeBooking(b.id,'Completed')}>Mark complete</button>}</div></article>):<div className="empty compact">No appointment requests yet. New demo bookings appear here.</div>}<p className="fineprint">*Revenue is calculated from completed bookings in this browser demo.</p></section>}
 {tab==='admin'&&<section className="container page"><p className="eyebrow">ADMIN CONTROL CENTRE</p><h1>Admin dashboard</h1><p className="muted">Booking records available in this demo session.</p><div className="stats"><div><span>Total users represented</span><b>{bookings.length?new Set(bookings.map(b=>b.customer)).size:0}</b></div><div><span>Total bookings</span><b>{bookings.length}</b></div><div><span>Completed revenue</span><b>₹{bookings.filter(b=>b.status==='Completed').reduce((n,b)=>n+b.price,0)}</b></div></div><div className="admin-tools"><div><h2>Booking data export</h2><p>Download the current demo booking records as a CSV spreadsheet.</p></div><button className="primary" onClick={exportCSV}>↓ Download CSV</button></div><h2 className="subheading">Booking records</h2>{bookings.length?bookings.map(b=><article className="owner-booking" key={b.id}><div><b>{b.customer} · {b.salon}</b><p>{b.service} · {b.slot} · ₹{b.price}</p><span className={'status status-'+b.status.toLowerCase()}>{b.status}</span></div></article>):<div className="empty compact">No demo records yet. Create a booking to populate this list.</div>}<p className="fineprint">This MVP does not yet use a shared user database. Export includes only records created in the current browser session.</p></section>}
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">RESERVE YOUR SLOT</p><h2>{selected.name}</h2><p className="muted">{selected.area} · ★ {selected.rating}</p><label>Service<select value={service} onChange={e=>setService(e.target.value)}>{selected.services.map(x=><option key={x}>{x}</option>)}</select></label><label>Choose your stylist<select value={stylist} onChange={e=>setStylist(e.target.value)}><option value="">Select stylist</option>{selected.stylists.map(x=><option key={x}>{x}</option>)}</select></label><label>Available time slots<div className="slotgrid">{slots.map(x=><button className={slot===x?'active':''} key={x} onClick={()=>setSlot(x)}>{x}</button>)}</div></label><div className="payment"><span>Estimated price</span><b>₹{selected.price}<small>Pay at salon · demo booking</small></b></div><button className="primary confirm" disabled={!stylist||!slot||!ownerOnline||salonStatus==='Fully booked'} onClick={confirm}>{!ownerOnline?'Salon offline':salonStatus==='Fully booked'?'Fully booked':'Request booking · ₹'+selected.price}</button><p className="fineprint">This is a demo request. Live salon-owner notifications and real-time slot locking need a connected backend.</p></div></div>}
 {showSignup&&<div className="overlay" onClick={()=>setShowSignup(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowSignup(false)}>×</button><p className="eyebrow">WELCOME TO TRIMZEE</p><h2>Create your account</h2><p className="muted">Choose your profile to open the right experience.</p><label>I am<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Choose account type</option><option value="customer">Customer</option><option value="owner">Salon / parlour owner</option><option value="admin">Admin</option></select></label>{role==='customer'&&<label>Gender for discovery<select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Choose</option><option value="male">Male — salons</option><option value="female">Female — parlours</option><option value="any">Show all</option></select></label>}<button className="primary confirm" disabled={!role||(role==='customer'&&!gender)} onClick={()=>{setShowSignup(false);setTab(role==='owner'?'owner':role==='admin'?'admin':'home');if(role==='customer'&&gender==='female')setQuery('parlour')}}>Continue →</button><p className="fineprint">Demo navigation only. Real accounts and persistent profile preferences need authentication and a database.</p></div></div>}
 <button className="chat-fab" onClick={()=>setChatOpen(v=>!v)} aria-label="Chat with Shubhiii">{chatOpen?'×':'☏'}<span>{chatOpen?'Close':'Shubhiii'}</span></button>
 {chatOpen&&<section className="chat-panel"><div className="chat-head"><div className="bot-avatar">S</div><div><b>Shubhiii</b><small>Trimzee booking assistant</small></div><button onClick={()=>setChatOpen(false)}>×</button></div><div className="chat-messages">{chatMessages.map((m,i)=><p className={m.startsWith('You:')?'mine':'theirs'} key={i}>{m}</p>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();sendChat()}}><input value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Ask Shubhiii for help…"/><button className="primary">➤</button></form></section>}
 <footer><div className="footer-inner"><button className="brand footer-brand" onClick={()=>setTab('home')}><span className="brandmark">T</span><span>TRIMZEE</span></button><span>Look good. Feel good. Book easy.</span><span>Made for Pune ✦</span></div></footer>
 </main>
}
